services:
  node-red:
    image: 5minds/node-red:node-red-contrib-processcube-4
    build:
      context: .
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Berlin
      - ENGINE_URL=http://engine:8000
    volumes:
      - ./nodered/:/data/
    depends_on:
      - engine
      - authority
  
  engine:
    image: 5minds/processcube_engine:2024-1
    ports:
      - 8000:8000
    volumes:
      - ./processes:/processes:ro
    environment:
      application__name: Engine for Node-RED contrib
      iam__baseUrl: http://authority:11560
      iam__allowAnonymousRootAccess: false
    command: --seed-dir=/processes --port 8000
    depends_on:
      - authority
    healthcheck:
      test: bash -c "[ -f /tmp/healthy ]"
      timeout: 1s
      retries: 20      

  authority:
    image: 5minds/processcube_authority:3.0.4
    ports:
      - 11560:11560
    volumes:
      - ./.processcube/authority/config:/etc/authority/config:ro
    environment:
      UPE_SEED_PATH: /etc/authority/config/upeSeedingData.json
