
services:
  node-red:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=Europe/Berlin
      - ENGINE_URL=http://engine:8000
      - FLOWS=/data/node-red-contrib-processcube-flows.json
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./node-red-data:/data

  engine:
    image: 5minds/processcube_engine:2024-1
    ports:
      - 8000:8000
    volumes:
      - ./processes:/processes:ro
    command: --seed-dir=/processes --port 8000
  authority:
    image: 5minds/processcube_authority:3.0.2-feature-17485d-lus47b1q
    ports:
      - 11560:11560
    volumes:
      - ./.processcube/authority/config:/etc/authority/config:ro
    environment:
      UPE_SEED_PATH: /etc/authority/config/upeSeedingData.json


networks:
  node-red-net: