services:
  node-red:
    image: 5minds/node-red:node-red-contrib-processcube
    build:
      context: .
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Berlin
      - ENGINE_URL=http://engine:8000
      - FLOWS=/nodered/node-red-contrib-processcube-flows.json
    volumes:
      - ./nodered/:/nodered/
  
  engine:
    image: 5minds/processcube_engine:2024-1
    ports:
      - 8000:8000
    volumes:
      - ./processes:/processes:ro
    command: --seed-dir=/processes --port 8000
